### ISSUE TITLE
Python wrapper idea

### ISSUE THREAD

**Issue by atorsvn** [inworld-ai/inworld-nodejs-sdk#17]
https://pypi.org/project/inworld-python/

**Comment by atorsvn** [comment]
https://github.com/atorsvn/inworld_python

**Comment by atorsvn** [comment]
Greatly simplified discord bot example

https://github.com/atorsvn/inworld_python/blob/main/example/discord_bot.py?fbclid=IwAR0e8Q2wX3J07GNW46haQ95uS0I-CHUjxytgVP32RzrsibkRNFE1czhrwf0

**Comment by realill** [comment]
Cool,
I would also recommend looking towards our Rest based Simple API https://docs.inworld.ai/docs/tutorial-api/
It does not support voice, but could what you need.
