### ISSUE TITLE
session expired or invalid error

### ISSUE THREAD

**Issue by caganDevApp** [inworld-ai/inworld-nodejs-sdk#28]
I cannot continue the session from where I left off. There is no problem with the first messages. After a while, when I send a message again, I get a session expired or invalid error.The error message I got is below.

Error: 9 FAILED_PRECONDITION: Session: 'default-d4dtvvgeew7x8bxfecdoqq:d74b1fa3-50cc-4f72-a00f-0a634d61460f' expired or invalid

**Comment by tshashkova** [comment]
You need to recreate connection when you get this error (Session  is expired or invalid)
Session is expired in about 30 minutes of inactivity
