### ISSUE TITLE
How to enable emoji responses

### ISSUE THREAD

**Issue by benjaminlim00** [inworld-ai/inworld-nodejs-sdk#54]
Hi devs, I am currently working on the discord bot typescript project example from this url:
https://github.com/inworld-ai/inworld-nodejs-sdk/tree/main/examples/ts/discord_bot

I am encountering a problem that I am unable to replicate, which is that the chatbot was able to include emoji responses as part of its generated response, but am no longer doing so.

I tried adding the emotion `true` flag as shown below, but I do not observe any difference in the generated output.
https://docs.inworld.ai/docs/tutorial-integrations/node/api

I will greatly appreciate any help 🙏

**Comment by RodrigoRVSN** [comment]
> I do not observe any difference in the generated output.

Looks like the difference is the `emotions` property with the `behavior` 🤔 

![image](https://github.com/inworld-ai/inworld-nodejs-sdk/assets/75763403/0e3372bc-907e-4f4a-953c-f709ba2b0a03)

**Comment by benjaminlim00** [comment]
for anyone who is facing a similar issue, I resolved it by removing `connection.close();` which was getting called on each `setOnMessage` event
