### ISSUE TITLE
Discord bot example doesnt have a memory

### ISSUE THREAD

**Issue by atorsvn** [inworld-ai/inworld-nodejs-sdk#7]
This 
Discord bot example doesnt seem to have a memory. and for some reason seems to generate a new session token with every interaction

**Comment by tshashkova** [comment]
@atorsvn I'm sure that sessionId (in our provided example) is kept while session is alive at the server side
Session on the server side is expired after 30 minutes of character inactivity
So you need to take it into account

If you use one sessionId, time difference between messages is less than 30 minutes, it should work
So if all condition are valid, but you see context is missed please provide an example here with sessionId and workspace resource name
